### ISSUE TITLE
MPS backend support

### ISSUE THREAD

**Issue by benpresles** [pmeier/light-the-torch#154]
Dear Philip Meier,

Is it possible for light-the-torch to support MPS backend (Apple Silicon) in the near future?

Thanks,
Ben

**Comment by pmeier** [comment]
Hey Beniot :wave: Correct me if I'm wrong, but I'm under the impression that the macOS wheel automatically includes support for the MPS backend. At least I cannot find any installation instructions. Are you facing any issues that would indicate the contrary?

**Comment by jamesobutler** [comment]
@benpresles You can check if your torch version has MPS support by reviewing https://pytorch.org/docs/2.5/notes/mps.html. Around PyTorch 1.13 was when MPS support started to be included. `light-the-torch` can install latest PyTorch versions, so give it a try and report back here with your results.

**Comment by benpresles** [comment]
My mistake. The problem I have does not come from light-the-torch, but from SlicerPyTorch (https://github.com/fepegar/SlicerPyTorch), which uses (badly?) light-the-torch to install the correct version of PyTorch.
- If I install ltt directly (in a virtual environment) and then PyTorch by doing "ltt install torch", the following wheel is downloaded https://download.pytorch.org/whl/cpu/torch-2.5.1-cp311-none-macosx_11_0_arm64.whl which supports MPS. Everything is fine.
- When I run SlicerPyTorch and ask the extension to install PyTorch, it downloads the following wheel https://download.pytorch.org/whl/cpu/torch-1.8.1-cp39-none-macosx_10_9_x86_64.whl which is an x86 wheel that does not support MPS.

**Comment by jamesobutler** [comment]
I suspect you previously downloaded an older torch version which is located in your [pip cache](https://pip.pypa.io/en/latest/cli/pip_cache/). On Windows this is located at "%LOCALAPPDATA%\pip\cache" and on macOS at "~/Library/Caches/pip".

SlicerPyTorch provides the PyTorch Utils module where you can specify a torch version requirement such as ">=1.12". Reminder to put that version requirement into the "Torch version requirement" field and not the "TorchVision version requirement" field.

See https://discourse.slicer.org/t/error-in-pytorch-installation/39880/10 for more details.

**Comment by benpresles** [comment]
First, I deleted my pip cache as suggested by running "python3 -m pip cache purge". Then I tried to install:
- PyTorch with SlicerPyTorch without specifying any version. As before, I get the x86 1.8.1 version.
- PyTorch with SlicerPyTorch specifying >=2.5. I get the following error: "ERROR: No matching distribution found for torch>=2.5".
- PyTorch with SlicerPyTorch specifying >=2.2. I get the x86 2.2.2 version.

Do I get x86 versions of PyTorch because Slicer 5.6.2 is Intel based?

**Comment by jamesobutler** [comment]
> PyTorch with SlicerPyTorch without specifying any version. As before, I get the x86 1.8.1 version.  
> PyTorch with SlicerPyTorch specifying >=2.2. I get the x86 2.2.2 version.

Good to hear that you were successful with updating the torch version by way of using SlicerPyTorch's PyTorch Utils and the torch version requirement field.

> Do I get x86 versions of PyTorch because Slicer 5.6.2 is Intel based?

3D Slicer only provides x86_64 binaries. That means the embedded python in the Slicer application is x86_64 based as well and why you get x86_64 torch whls. The 3D Slicer application runs on your macOS machine through Rosetta 2. Slicer does not currently provide native ARM64 binaries. Adding ARM64 support is currently being tracked in https://github.com/Slicer/Slicer/issues/6811.

For now, you will have to use latest `torch` 2.2.x as `torch` deprecated x86 builds on macOS for all newer versions.
https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690

**Comment by benpresles** [comment]
OK, thanks for your help and explanation. So I guess I have to wait for an ARM64 version of Slicer to get an ARM64-based embedded version of Python, so I can get an AMR64-based version of PyTorch that supports MPS, right? Do you know when an Apple Silicon version of Slicer will be available?

**Comment by jamesobutler** [comment]
Yes that is correct. There is no official timeline for native ARM64 binaries for use on Apple Silicon. I would guess not likely before March 2025.
