### ISSUE TITLE
Remove `ltt extract` and `ltt find`?

### ISSUE THREAD

**Issue by pmeier** [pmeier/light-the-torch#41]
Hey @fepegar and @H00N24. I'm sorry I'm pulling you into this, but I don't want to take this step without user feedback. In #40 it became clear that with `pip`'s new dependency resolver the current implementation of `light-the-torch` no longer works. In fact, going forward it will particularly hard to support `ltt extract` and `ltt find` while `ltt install` will probably even easier to support.

My question for you now is: would that be a problem for your use cases or are you only using `ltt install` anyway? I had some use cases for the other commands in the past, but looking back at my usage in the last year, I haven't used them.

**Comment by fepegar** [comment]
Being pulled for feedback is the least we can do to thank you for publishing this.

I typically use `ltt install` only. In the [3D Slicer extension](https://github.com/fepegar/SlicerPyTorch/blob/d061471c1466859afc12dcca1ff567810cbf2894/PyTorchUtils/PyTorchUtils.py#L104-L115), I use `ltt.find_links`. That's all.

**Comment by pmeier** [comment]
I should have been more clear here. Removing `ltt extract` and `ltt find` would also entail removing `ltt.extract_dists` and `ltt.find_links`. I'll have a look how it is used now in your extension to see if I can retain functionality.

**Comment by pmeier** [comment]
@fepegar 

1. Could you help me find the code that is called [here](https://github.com/fepegar/SlicerPyTorch/blob/d061471c1466859afc12dcca1ff567810cbf2894/PyTorchUtils/PyTorchUtils.py#L99)?
2. It seems you are using it to "only" find the right PyTorch wheel in an otherwise fully unconstrained problem. So you basically only need computation backend detection followed by a direct lookup of the right wheel rather than more complicated resolving. That can be supported even if the more general functionality goes away.

**Comment by fepegar** [comment]
1. Sure! It's [here](https://github.com/Slicer/Slicer/blob/8862378cd995420e0ace3622c1d9ac9e66349b3f/Base/Python/slicer/util.py#L3151-L3174)
2. Yes, that sounds right. It's a very basic usage.

**Comment by H00N24** [comment]
Hi, sorry for the late response. I was using only `ltt install`, so I don't have any specific use case for `extract` and `find`. 
I was using `light-the-torch` as a quick way to install PyTorch on servers for testing if CUDA is installed correctly and everything is working. For production, I'm trying to stick with a precise version (including CUDA/CPU tag, etc.) in the `requirements.txt` file generated by `pip-tools` or `poetry`.

**Comment by pmeier** [comment]
Thanks for the input @fepegar and @H00N24!
